### ISSUE TITLE
any plans to support later versions of lua (5.2 & 5.3)?

### ISSUE THREAD

**Issue by doddt** [iponweb/luavela#11]
We would like to be able to take advantage of some of the features of lua versions > 5.1.

**Comment by eliasdaler** [comment]
Hello. There are no such plans, as that will require a huge amount of work, for which we don't have resources.

**Comment by nico-abram** [comment]
From the small FAQ sent to the mailing list:

Q: What about support for Lua 5.2+?

A: Unfortunately, we do not have resources to implement it on our own.
However, patches are welcome. We definitely do *not* plan to increase
the compatibility gap with the PUC-Rio implementation. E.g. dropping
support for C API or any initiative like this is not an option for the
project.
