### ISSUE TITLE
Segfault after lua_yield()

### ISSUE THREAD

**Issue by neoxic** [iponweb/luavela#12]
LuaVela as a drop-in replacement crashes in our environment where Lua threads are used extensively. Please see the following code snippet that illustrates the problem:
```c
#include <lauxlib.h>
#include <lualib.h>

static int yield(lua_State *L) {
    return lua_yield(L, lua_gettop(L));
}

int main(void) {
    lua_State *L = luaL_newstate();
    lua_State *T = lua_newthread(L);
    lua_pushcfunction(L, yield);
    lua_setglobal(L, "yield");
    luaL_openlibs(L);
    luaL_loadstring(T, "print('ENTER #1');yield();print('LEAVE #1')");
    lua_resume(T, 0); /* ENTER #1 */
    lua_resume(T, 0); /* LEAVE #1 */
    /* Normally finished thread can be reused - https://www.lua.org/manual/5.3/manual.html#lua_status */
    luaL_loadstring(T, "print('ENTER #2');yield();print('LEAVE #2')");
    lua_resume(T, 0); /* ENTER #2 */
    lua_resume(T, 0); /* LEAVE #2 */
    lua_close(L);
    return 0;
}
```
Expected output:
```
ENTER #1
LEAVE #1
ENTER #2
LEAVE #2
```
Observed output:
```
ENTER #1
Segmentation fault (core dumped)
```
Output under gdb:
```
...
(gdb) r
Starting program: /mnt/seny/devel/tmp/a.out
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
ENTER #1

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7e71a79 in lj_BC_RET () from /home/seny/local/lib/libujit.so.0
(gdb) bt
#0  0x00007ffff7e71a79 in lj_BC_RET () from /home/seny/local/lib/libujit.so.0
#1  0x00007ffff7e9f91b in lua_resume (L=0x7ffff7acb338, nargs=0) at /home/seny/devel/luavela/src/uj_capi.c:1037
#2  0x0000555555555274 in main () at ujit1.c:15
```

**Comment by neoxic** [comment]
Hmm... Is this project alive?

**Comment by igelhaus** [comment]
Hi @neoxic,

Thanks for the spotted bug, and it's a pity that it remained unnoticed for a long time. Hope to have it fixed if the guys accept #19.

> Hmm... Is this project alive?

This is a more interesting question, though. To the best of my knowledge, this project is alive meaning that it is still actively used in production by its creators. However, I don't know if it is actively developed right now, @eliasdaler can provide more up-to-date info on this (and about maintenance policy as well, I guess).

**Comment by neoxic** [comment]
Hello @igelhaus ! Thanks for the fix and the information! We would like to give LuaVela a try in our production environment as a drop-in replacement for LuaJIT. Hopefully, things will get moving again after your PR gets accepted.

**Comment by igelhaus** [comment]
> Hello @igelhaus ! Thanks for the fix and the information! We would like to give LuaVela a try in our production environment as a drop-in replacement for LuaJIT. Hopefully, things will get moving again after your PR gets accepted.

@neoxic I see. Might be quite an interesting experience. I will be keeping an eye on the list of issues in this repo then. Feel free to mention me if you need help. I’m no longer with IPONWEB, but I was involved into development of LuaVela for several years.

**Comment by neoxic** [comment]
Will do, @igelhaus! Thanks again!
