### ISSUE TITLE
aux.* is a reserved filename on windows

### ISSUE THREAD

**Issue by Fuzzlix** [iponweb/luavela#15]
On windows(10) I get the following error during checkout:

error: unable to stat just-written file tests/impl/uJIT-tests-Lua/suite/chunks/profile-leaf/aux.lua: No such file or directory

I tried to manually write the file on disk and figured out, win10 does not allow any "aux.*" filenames. 

Can you rename the aux.lua file? Thank you.

**Comment by craigbarnes** [comment]
According to [this blog post](https://eliasdaler.github.io/luavela/) it's Linux x86_64 only:

> Another thing that was done early on was dropping cross-platform support. We used LuaVela for projects which ran on x86-64 Linux only and it was difficult for our small team to try to support all the other platforms.

Also:

> At the moment, the development of LuaVela is finished. We’ll fix critical bugs, but we felt that LuaVela is close to being feature complete and fast enough for most of our use cases, so we’ve moved on to other projects. LuaVela was open sourced as a “thank you” for Lua and LuaJIT community and developers. I hope that some of the unique things LuaVela has will be later ported to other active forks

**Comment by igelhaus** [comment]
Wow. Thanks for letting know anyway.

> it's Linux x86_64 only

It is true. But I'm inclined to submit a pull request anyway (in progress).
