### ISSUE TITLE
Unused result of `fgets()` in `src/dump/uj_dump_bc.c`

### ISSUE THREAD

**Issue by sofar** [iponweb/luavela#2]
My compiler warnings are only paranoid, but not crazy, so I get this when I compile:

```
/home/sofar/git/luavela/src/dump/uj_dump_bc.c: In function ‘dump_bc_get_file_line’:
/home/sofar/git/luavela/src/dump/uj_dump_bc.c:296:2: error: ignoring return value of ‘fgets’, declared with attribute warn_unused_result [-Werror=unused-result]
  296 |  fgets(sds->buf, MAX_SRC_LINE_LEN + 2, sds->file);
      |  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Would be good to have this fixed, since `fgets` may return `NULL` on error, and you really want to at least do something with that. (Don't be like me and `if (!fgets()) return` though, that probably won't be the right solution here). :)

**Comment by eliasdaler** [comment]
I think here we should probably assert that non-NULL value is returned by `fgets`, otherwise there's nothing we can do to recover, I think.
Can you please tell me what compiler you're using so that we can reproduce it?

**Comment by sofar** [comment]
This is a stock `clearlinux` install

```
$ gcc --version
gcc (Clear Linux OS for Intel Architecture) 9.1.1 20190807 gcc-9-branch@274154
```

There's a few little patches to the compiler, they're over here:
    https://github.com/clearlinux-pkgs/gcc

Clearlinux does ship with some CFLAGS by default, e.g.

```
CFLAGS='-g -O3 -feliminate-unused-debug-types  -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=32 -Wformat -Wformat-security -m64  -fasynchronous-unwind-tables -Wp,-D_REENTRANT -ftree-loop-distribute-patterns -Wl,-z -Wl,now -Wl,-z -Wl,relro -fno-semantic-interposition -ffat-lto-objects  -fno-signed-zeros -fno-trapping-math  -fassociative-math -Wl,-sort-common -Wl,--enable-new-dtags -mtune=skylake'
```
