### ISSUE TITLE
LuaJIT 2.0 differences documentation?

### ISSUE THREAD

**Issue by nico-abram** [iponweb/luavela#22]
Hello!

I just found this project. I was wondering if you have any documentation which detais the differences beween this and luajit. The post sent to the mailing list is the most I've found so far (http://lua-users.org/lists/lua-l/2019-08/msg00041.html).

I'm particularly curiuous about the behaviour of what that post describes as "Coroutine timeouts". Is that essentially pre-emption from coroutines? How does it interact with jit-compiled code?

Thanks for sharing this project!

**Comment by eliasdaler** [comment]
Hello. Yes, this is a pre-emption from coroutines.
You can find more implementation details here: https://github.com/iponweb/luavela/blob/master/docs/public/spec-coroutine-timeouts.rst

And perhaps @igelhaus can give insights about how coroutine timeouts interact with jit-compiled code?

**Comment by eliasdaler** [comment]
@igelhaus can you answer this question, please? :)

**Comment by igormunkin** [comment]
@nico-abram, thanks for your interest!

[Here](https://github.com/iponweb/luavela/blob/master/docs/public/spec-coroutine-timeouts.rst) is a spec for "Coroutine timeouts". You can find a [section with caveats](https://github.com/iponweb/luavela/blob/master/docs/public/spec-coroutine-timeouts.rst#implementation-limitations-and-caveats) that also contains information related to interaction with JIT-compiled code. Feel free to ask more in this thread so we can enhance our docs regarding your questions.

**Comment by igelhaus** [comment]
Hi all,

Sorry for delayed reply. Actually I have nothing to add to what was already answered.

@nico-abram, if you still have any questions, feel free to ask.

**Comment by eliasdaler** [comment]
Closing, because the answer has been answered. Feel free to ask more questions (and even re-open) if more questions arise.
