### ISSUE TITLE
Using LuaVela as a drop-in-replacement, - segmentation fault in lua_tolstring

### ISSUE THREAD

**Issue by pkpro** [iponweb/luavela#5]
Hi guys, I was excited to find out about your project. And of course tried to immediatelly test it.

And I have stumbled on segmentation fault in the code that works normally with LuaJIT and the Lua.

The problematic part of the code looks like this:
  if(lua_isstring(L,udidx))
  {
    size_t len;
    const char* msg=lua_tolstring(L,udidx,&len); /// SEGFAULT here
....

Regards,
Pavel
P.S.: if you need more context on this matter, I can provide all the sources or the part of them. The full project is too large for this matter anyways it is here: https://github.com/ITpC/LAppS
Or we can make a debugging session together over anydesk for example.

**Comment by eliasdaler** [comment]
Hello.
When you compile LuaVela - do all tests pass? (run `make -j tests_full`)

Can you also provide more complete stack trace? `lua_tolstring` should crash somewhere internally. It might also be helpful if you point out the place in LAppS project where the crash happens and how we can reproduce it, seeing that it's open source and we can build it and debug it locally to try to find the root cause.

**Comment by pkpro** [comment]
It seems not all the tests could pass because I do not have installed everything requited for them to pass.

LANG=C LC_ALL=C make tests_full > test_full.log
sh: __IMPROBABLE__: command not found
lua_debug> lua_debug> (debug command):1: dbg
lua_debug> No clang-format found at scripts/run-clang-format line 210.
make[3]: *** [CMakeFiles/clang_format.dir/build.make:58: CMakeFiles/clang_format] Error 2
make[2]: *** [CMakeFiles/Makefile2:73: CMakeFiles/clang_format.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:216: CMakeFiles/tests_full.dir/rule] Error 2
make: *** [Makefile:216: tests_full] Error 2

[test_full.log](https://github.com/iponweb/luavela/files/3560465/test_full.log)


LANG=C LC_ALL=C make -j tests_full > test_full1.log
No clang-tidy found at ../../../../scripts/run-clang-tidy line 176.
make[3]: *** [tests/impl/uJIT-tests-C/suite/CMakeFiles/clang_tidy_tests.dir/build.make:101: tests/impl/uJIT-tests-C/suite/CMakeFiles/clang_tidy_tests] Error 2
make[2]: *** [CMakeFiles/Makefile2:2104: tests/impl/uJIT-tests-C/suite/CMakeFiles/clang_tidy_tests.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....
No clang-format found at scripts/run-clang-format line 210.
make[3]: *** [CMakeFiles/clang_format.dir/build.make:58: CMakeFiles/clang_format] Error 2
make[2]: *** [CMakeFiles/Makefile2:73: CMakeFiles/clang_format.dir/all] Error 2
/usr/lib/python-exec/python3.6/python3: No module named flake8
make[3]: *** [CMakeFiles/flake8.dir/build.make:58: CMakeFiles/flake8] Error 1
make[2]: *** [CMakeFiles/Makefile2:105: CMakeFiles/flake8.dir/all] Error 2
No clang-tidy found at ../scripts/run-clang-tidy line 176.
make[3]: *** [tools/CMakeFiles/clang_tidy_tools.dir/build.make:72: tools/CMakeFiles/clang_tidy_tools] Error 2
make[2]: *** [CMakeFiles/Makefile2:3370: tools/CMakeFiles/clang_tidy_tools.dir/all] Error 2
No clang-tidy found at ../scripts/run-clang-tidy line 176.
make[3]: *** [src/CMakeFiles/clang_tidy_core.dir/build.make:160: src/CMakeFiles/clang_tidy_core] Error 2
make[2]: *** [CMakeFiles/Makefile2:601: src/CMakeFiles/clang_tidy_core.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:216: CMakeFiles/tests_full.dir/rule] Error 2
make: *** [Makefile:216: tests_full] Error 2

[test_full1.log](https://github.com/iponweb/luavela/files/3560478/test_full1.log)
                                              

I did more proper debugging this time and Im convinced that the problem not  in lua_to_string. I will close this issue. I will need to spend more time with debugging.
