### ISSUE TITLE
lua_tointeger() incapable to convert into 64-bit integers.

### ISSUE THREAD

**Issue by pkpro** [iponweb/luavela#6]
Hi guys, I found where the issue with segfault was. It was not lua_tolstring().

After some debugging I found that lua_tointeger() behaves differently in Lua/LuaJIT and LuaVela.

Here is the testcase (testluapi.cpp):

#ifdef VELA
extern "C" {
#include <ujit/lua.h>
#include <ujit/lualib.h>
#include <ujit/lauxlib.h>
}
#else
extern "C" {
#include <ujit/lua.h>
#include <ujit/lualib.h>
#include <ujit/lauxlib.h>
}
#endif

int main()
{
  lua_State*  L=luaL_newstate();
  luaL_openlibs(L);

// putting large integer into lua: 7f210b001810
  lua_pushinteger(L,0x7f210b001810LL);
  lua_setfield(L, LUA_GLOBALSINDEX,  "bigint");

// printing out large integer from lua: b001810 for VELA
// and correct 7f210b001810 for Lua/LuaJIT

  luaL_dostring(L,"print(string.format('%X',bigint))");
}

---- and here is how does it work with different Lua variants---

6415:pk@friskr > gcc -fPIC ./testluapi.cpp -lluajit-5.1 -ldl

[~/test]
16416:pk@friskr > ./a.out 
7F210B001810

[~/test]
16417:pk@friskr > gcc -DVELA -fPIC ./testluapi.cpp -lujit -ldl

[~/test]
16418:pk@friskr > ./a.out 
B001810

[~/test]
16419:pk@friskr > gcc -fPIC ./testluapi.cpp -llua -ldl

[~/test]
16420:pk@friskr > ./a.out 
7F210B001810

----------------

Here is the difference in lua_tointeger (LuaJIT-2.0.5, lj_api.c):

``LUA_API` lua_Integer lua_tointeger(lua_State *L, int idx)
{
  cTValue *o = index2adr(L, idx);
  TValue tmp;
  lua_Number n;
  if (LJ_LIKELY(tvisint(o))) {
    return intV(o);
  } else if (LJ_LIKELY(tvisnum(o))) {
    n = numV(o);
  } else {
    if (!(tvisstr(o) && lj_strscan_number(strV(o), &tmp)))
      return 0;
    if (tvisint(&tmp))
      return (lua_Integer)intV(&tmp);
    n = numV(&tmp);
  }
#if LJ_64
  return (lua_Integer)n;
#else
  return lj_num2int(n);
#endif
}

-------- LuaVela uj_capi.c --------------
``LUA_API lua_Integer lua_tointeger(lua_State *L, int idx)
{
  return (lua_Integer)lua_tonumber(L, idx);
}

-----------

Yes it is way faster, but incapable to convert into 64-bit integers.

One more thing, conversion strings within Lua with tonumber() works fine. If we add to above testcase following lines:

-----

// pushing string representing same integer
  lua_pushstring(L,"139779895203856");
  lua_setfield(L, LUA_GLOBALSINDEX,  "bigint");
  luaL_dostring(L,"print(string.format('%X',tonumber(bigint)))");

----
It will print out correct hex number.

Regards,
Pavel.

**Comment by eliasdaler** [comment]
Can confirm the regression. Thanks for the clear minimal repro. :)
We'll take a look into it soon.
